Symbol ::= "|" ;
Symbol ::= "-" ;
Symbol ::= "!" ;
Symbol ::= "#" ;
Symbol ::= "$" ;
Symbol ::= "%" ;
Symbol ::= "&" ;
Symbol ::= "(" ;
Symbol ::= ")" ;
Symbol ::= "*" ;
Symbol ::= "+" ;
Symbol ::= "," ;
Symbol ::= "." ;
Symbol ::= "/" ;
Symbol ::= ":" ;
Symbol ::= ";" ;
Symbol ::= "<" ;
Symbol ::= "=" ;
Symbol ::= ">" ;
Symbol ::= "?" ;
Symbol ::= "@" ;
Symbol ::= "[" ;
Symbol ::= "\\" ;
Symbol ::= "]" ;
Symbol ::= "^" ;
Symbol ::= "_" ;
Symbol ::= "`" ;
Symbol ::= "{" ;
Symbol ::= "}" ;
Symbol ::= "~" ;
