Uppercase ::= "A" ;
Uppercase ::= "B" ;
Uppercase ::= "C" ;
Uppercase ::= "D" ;
Uppercase ::= "E" ;
Uppercase ::= "F" ;
Uppercase ::= "G" ;
Uppercase ::= "H" ;
Uppercase ::= "I" ;
Uppercase ::= "J" ;
Uppercase ::= "K" ;
Uppercase ::= "L" ;
Uppercase ::= "M" ;
Uppercase ::= "N" ;
Uppercase ::= "O" ;
Uppercase ::= "P" ;
Uppercase ::= "Q" ;
Uppercase ::= "R" ;
Uppercase ::= "S" ;
Uppercase ::= "T" ;
Uppercase ::= "U" ;
Uppercase ::= "V" ;
Uppercase ::= "W" ;
Uppercase ::= "X" ;
Uppercase ::= "Y" ;
Uppercase ::= "Z" ;
