=head1 NAME

prompt

=head1 SYNOPSIS

use prompt;
string var;

var = prompt("Are you ok?(Y/N)");
if (var eq "Y") {
	print "I'm glad.\n";
} else {
	print "I'm sorry, I hope you feel better soon.\n";
}

=head1 DESCRIPTION

The prompt function allows you to simplify prompting the user for input.
It displays a prompt which is passed in then returns the value input.

=head1 RETURN VALUE

=head1 EXAMPLES


=head1 SEE ALSO

printf
