
comment = '//'
comment = '/*' '*/'
comment = '#'

entrypoints Program

Program = ''
Program = Fundef Program
Program = Vardef Program
Program = Pkg Program

# Note this 
Fundef = [TypeDefl] Type Ident Params Block
Fundef = [TypeDefl] Type "*" Ident Params Block

Params = '(' ')' 
Params = '(' Plist ')' 

Plist = Param
Plist = Param ',' Plist

Vardef = [Typedefl] Type Varcall ';'
Vardef = [Typedefl] Type '*' Varcall ';'	# Code doesn't use * yet...

Pkg = 'use' Conststr  # Instead of inherit or include

Block = '{'  '}'
Block = '{' Statements '}'

Statements = ''
Statements = ';'
Statements = Stm Statements

Stm = ';'
Stm = Exp ';'
Stm = Block
Stm = While
Stm = Do_While
Stm = Return
Stm = If
Stm = Print
Stm = Goto
Stm = Label
Stm = Return
Stm = Exit 
Stm = Break 
Stm = Foreach
Stm = Exp_list
Stm = Switch

Foreach = 'foreach' Ident '(' Exp ')' Block
While = 'while' '(' Exp ')' Block
If = 'if' '(' Exp ')' Block
If = 'if' '(' Exp ')' Block 'else' Block
Switch = 'switch' '(' Exp ')' Switch_Block
Do_While = 'do' Block 'while' '(' Exp ')' ';'
Return = 'return' Exp ';'
Exit = 'Exit' Exp ';'
Print = 'print' Exp ';'
Label = 'label' Ident ';'
Break = 'break' ';'
Goto = 'goto' Exp ';'
Exp_list = '(' Exp ')'

Switch_block = '{' Case_list Default '}'

Case_list = ''
Case_list = Case Case_list

Case = 'case' '{' Statements '}'

Default = 'default' '{' Statements '}'

Exp = Ident '=' Exp
Exp = Bracket
Exp = Exp Binop Exp
Exp = Unop Exp
Exp = Const

Bracket = '(' Exp ')'

Const = String
Const = Num
Const = Varcall
Const = Funcall

Binop = '||'
Binop = '&&'
Binop = '=='
Binop = '!='
Binop '+='
Binop '-='
Binop '>'
Binop '<'
Binop '>='
Binop '<='
Binop '+'
Binop '-'
Binop '*'
Binop '/'

Unop = '-'
Unop = '+'

Varcall = Ident 
Varcall = Ident '[' ']'
Varcall = Ident '[' Exp ']'

Funcall = ident Exp_list

Exp_list = '(' ')'
Exp_list = '(' Exp_l ')'
Exp_l = Exp
Exp_l = Exp ',' Exp_l

Type = 'void'
Type = 'int'
Type = 'float'
Type = 'string'
Type = 'object'
Type = 'hash'
Type = 'mixed'

TypeDef = 'atomic'
TypeDef = 'nomask'
TypeDef = 'private'
TypeDef = 'static'

TypeDefl = ''
TypeDefl = TypeDef
TypeDefl = TypeDef TypeDefl

